uploads = []

[[generated]]
id = "vvHov-deasuv-oeJ2Ngo9"
uri = "file://public/images/mascot-clean.png"
type = "image"
title = "mascot background removed"

[[outputs]]
id = "bereuAFiaTV6gOHhvqeWq"
uri = "file://.local/seo/missing-crm-leads-2026-04-19.json"
type = "unspecified"
title = "missing-crm-leads-2026-04-19.json (10 leadov pre bulk import)"
