import { MetadataRoute } from "next";
import { blogPosts } from "@/lib/blog";

const BASE_URL = "https://www.sofoservis.sk";

export default function sitemap(): MetadataRoute.Sitemap {
  const blogRoutes: MetadataRoute.Sitemap = blogPosts.map((post) => ({
    url: `${BASE_URL}/blog/${post.slug}`,
    changeFrequency: "monthly" as const,
    priority: 0.65,
    lastModified: new Date(post.publishDate),
  }));

  const staticRoutes: MetadataRoute.Sitemap = [
    { url: `${BASE_URL}/`, changeFrequency: "weekly", priority: 1.0 },

    { url: `${BASE_URL}/stahovanie-bratislava`, changeFrequency: "weekly", priority: 0.9 },
    { url: `${BASE_URL}/stahovanie-bytov-domov`, changeFrequency: "weekly", priority: 0.9 },
    { url: `${BASE_URL}/stahovanie-kancelarii-firiem`, changeFrequency: "weekly", priority: 0.9 },
    { url: `${BASE_URL}/vypratavanie-bytov-domov`, changeFrequency: "weekly", priority: 0.9 },

    { url: `${BASE_URL}/hodinovy-manzel-majster`, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/montaz-nabytku`, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/montaz-kuchyne`, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/stahovanie-tazkych-bremien`, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/medzinarodne-stahovanie`, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/stahovanie-na-slovensko`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/stahovanie-zo-slovenska`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/stahovanie-z-anglie-na-slovensko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/stahovanie-z-nemecka-na-slovensko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/stahovanie-z-rakuska-na-slovensko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/stahovanie-z-francuzska-na-slovensko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/stahovanie-z-holandska-na-slovensko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/stahovanie-z-usa-na-slovensko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/stahovanie-preprava-nabytku`, changeFrequency: "weekly", priority: 0.8 },

    { url: `${BASE_URL}/cistenie-vypratavanie-pozemkov-nehnutelnosti`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/vypratavanie-odvoz-stareho-nabytku`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/vypratavanie-pivnic-garazi-nebytovych-priestorov`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/odvoz-likvidacia-stavebneho-odpadu`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/likvidacia-nebezpecneho-odpadu-starych-spotrebicov`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/buracie-demolacne-prace`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/buranie-demolacia-domov-bytov`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/buranie-stien-priecok`, changeFrequency: "weekly", priority: 0.7 },

    { url: `${BASE_URL}/stahovanie-petrzalka`, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/stahovanie-ruzinov`, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/stahovanie-stare-mesto`, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/stahovanie-nove-mesto`, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/stahovanie-karlova-ves`, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/stahovanie-dubravka`, changeFrequency: "weekly", priority: 0.8 },

    { url: `${BASE_URL}/vypratavanie-bratislava`, changeFrequency: "weekly", priority: 0.85 },
    { url: `${BASE_URL}/vypratavanie-petrzalka`, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/vypratavanie-ruzinov`, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/vypratavanie-stare-mesto`, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/vypratavanie-nove-mesto`, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/vypratavanie-karlova-ves`, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE_URL}/vypratavanie-dubravka`, changeFrequency: "weekly", priority: 0.8 },

    { url: `${BASE_URL}/montaz-nabytku/bratislava`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/hodinovy-manzel-majster/bratislava`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/vypratavanie-bytov-domov/bratislava`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/vypratavanie-odvoz-stareho-nabytku/bratislava`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/vypratavanie-pivnic-garazi-nebytovych-priestorov/bratislava`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/odvoz-likvidacia-stavebneho-odpadu/bratislava`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/buracie-demolacne-prace/bratislava`, changeFrequency: "weekly", priority: 0.7 },

    { url: `${BASE_URL}/stahovanie-nitra`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/stahovanie-trnava`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/stahovanie-senec`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/stahovanie-pezinok`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/stahovanie-malacky`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/stahovanie-galanta`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/stahovanie-piestany`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/stahovanie-sala`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/stahovanie-hlohovec`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/stahovanie-levice`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/stahovanie-komarno`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/stahovanie-samorin`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/stahovanie-stupava`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/stahovanie-senica`, changeFrequency: "weekly", priority: 0.7 },

    { url: `${BASE_URL}/vypratavanie-trnava`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/vypratavanie-pezinok`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/vypratavanie-senica`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/vypratavanie-nitra`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/vypratavanie-hlohovec`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/vypratavanie-komarno`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/vypratavanie-levice`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/vypratavanie-senec`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/vypratavanie-piestany`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/vypratavanie-galanta`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/vypratavanie-malacky`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/vypratavanie-samorin`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/vypratavanie-stupava`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/vypratavanie-sala`, changeFrequency: "weekly", priority: 0.75 },

    { url: `${BASE_URL}/vypratavanie-bytov-domov/trnava`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/vypratavanie-bytov-domov/nitra`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/vypratavanie-bytov-domov/senec`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/vypratavanie-bytov-domov/pezinok`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/vypratavanie-bytov-domov/galanta`, changeFrequency: "weekly", priority: 0.70 },
    { url: `${BASE_URL}/vypratavanie-bytov-domov/sala`, changeFrequency: "weekly", priority: 0.70 },
    { url: `${BASE_URL}/vypratavanie-bytov-domov/hlohovec`, changeFrequency: "weekly", priority: 0.70 },
    { url: `${BASE_URL}/vypratavanie-bytov-domov/senica`, changeFrequency: "weekly", priority: 0.70 },
    { url: `${BASE_URL}/vypratavanie-bytov-domov/malacky`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/vypratavanie-bytov-domov/levice`, changeFrequency: "weekly", priority: 0.70 },
    { url: `${BASE_URL}/vypratavanie-bytov-domov/komarno`, changeFrequency: "weekly", priority: 0.70 },
    { url: `${BASE_URL}/vypratavanie-bytov-domov/piestany`, changeFrequency: "weekly", priority: 0.70 },
    { url: `${BASE_URL}/vypratavanie-bytov-domov/samorin`, changeFrequency: "weekly", priority: 0.70 },
    { url: `${BASE_URL}/vypratavanie-bytov-domov/stupava`, changeFrequency: "weekly", priority: 0.75 },

    { url: `${BASE_URL}/vypratavanie-pozostalosti`, changeFrequency: "weekly", priority: 0.80 },
    { url: `${BASE_URL}/vypratavanie-kancelarii`, changeFrequency: "weekly", priority: 0.80 },
    { url: `${BASE_URL}/vypratavanie-po-rekonstrukcii`, changeFrequency: "weekly", priority: 0.80 },
    { url: `${BASE_URL}/vypratavanie-chalupy`, changeFrequency: "weekly", priority: 0.75 },

    { url: `${BASE_URL}/hodinovy-manzel-majster/nitra`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/hodinovy-manzel-majster/trnava`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/hodinovy-manzel-majster/galanta`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/hodinovy-manzel-majster/piestany`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/hodinovy-manzel-majster/sala`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/hodinovy-manzel-majster/levice`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/buracie-demolacne-prace/nitra`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/buracie-demolacne-prace/trnava`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/buracie-demolacne-prace/pezinok`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/odvoz-likvidacia-stavebneho-odpadu/nitra`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/odvoz-likvidacia-stavebneho-odpadu/trnava`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/odvoz-likvidacia-stavebneho-odpadu/senec`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/odvoz-likvidacia-stavebneho-odpadu/galanta`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/odvoz-likvidacia-stavebneho-odpadu/hlohovec`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/odvoz-likvidacia-stavebneho-odpadu/senica`, changeFrequency: "weekly", priority: 0.65 },

    { url: `${BASE_URL}/blog`, changeFrequency: "weekly", priority: 0.7 },

    { url: `${BASE_URL}/o-nas`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE_URL}/cennik`, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE_URL}/referencie`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/kontakt`, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE_URL}/zasady-pouzivania-cookies`, changeFrequency: "yearly", priority: 0.2 },
    { url: `${BASE_URL}/zasady-spracovania-osobnych-udajov`, changeFrequency: "yearly", priority: 0.2 },
    { url: `${BASE_URL}/vseobecne-obchodne-podmienky`, changeFrequency: "yearly", priority: 0.3 },

    { url: `${BASE_URL}/en`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/en/about`, changeFrequency: "monthly", priority: 0.75 },
    { url: `${BASE_URL}/en/moving-bratislava`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/apartment-moving`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/office-moving`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/furniture-assembly`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/handyman-services`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/kitchen-installation`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/international-moving-services`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/moving-heavy-loads`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/furniture-moving-removal`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/furniture-removal`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/home-junk-removal`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/basement-garage-junk-removal`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/construction-waste-removal`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/hazardous-waste-removal`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/demolition-services`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/house-demolition`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/wall-demolition`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/property-land-junk-removal`, changeFrequency: "weekly", priority: 0.65 },

    { url: `${BASE_URL}/en/home-junk-removal-bratislava`, changeFrequency: "weekly", priority: 0.6 },
    { url: `${BASE_URL}/en/basement-junk-removal-bratislava`, changeFrequency: "weekly", priority: 0.6 },
    { url: `${BASE_URL}/en/old-furniture-removal-bratislava`, changeFrequency: "weekly", priority: 0.6 },
    { url: `${BASE_URL}/en/furniture-assembly-bratislava`, changeFrequency: "weekly", priority: 0.6 },
    { url: `${BASE_URL}/en/handyman-bratislava`, changeFrequency: "weekly", priority: 0.6 },
    { url: `${BASE_URL}/en/demolition-bratislava`, changeFrequency: "weekly", priority: 0.6 },
    { url: `${BASE_URL}/en/construction-waste-removal-bratislava`, changeFrequency: "weekly", priority: 0.6 },

    { url: `${BASE_URL}/en/moving-nitra`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-trnava`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-senec`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-pezinok`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-malacky`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-galanta`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-piestany`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-sala`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-hlohovec`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-levice`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-komarno`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-samorin`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-stupava`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-senica`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/handyman-nitra`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/handyman-trnava`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/handyman-galanta`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/handyman-piestany`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/handyman-sala`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/handyman-levice`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/demolition-nitra`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/demolition-trnava`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/demolition-pezinok`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/construction-waste-removal-nitra`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/construction-waste-removal-trnava`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/construction-waste-removal-senec`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/construction-waste-removal-galanta`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/construction-waste-removal-hlohovec`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/construction-waste-removal-senica`, changeFrequency: "weekly", priority: 0.55 },

    { url: `${BASE_URL}/medzinarodne-stahovanie/amsterdam`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/barcelona`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/berlin`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/brusel`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/budapest`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/dublin`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/frankfurt`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/hamburg`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/kodane`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/lisabon`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/londyn`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/mnichov`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/oslo`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/pariz`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/praha`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/rim`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/stockholm`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/varsava`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/vieden`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/zurich`, changeFrequency: "monthly", priority: 0.65 },

    { url: `${BASE_URL}/en/moving-to-belgium`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-brno`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-czech-republic`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-denmark`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-hungary`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-poland`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-spain`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-italy`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-amsterdam`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-barcelona`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-berlin`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-brussels`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-budapest`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-copenhagen`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-dublin`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-frankfurt`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-hamburg`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-lisbon`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-london`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-munich`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-oslo`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-paris`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-prague`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-rome`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-stockholm`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-vienna`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-warsaw`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-zurich`, changeFrequency: "monthly", priority: 0.6 },


    { url: `${BASE_URL}/en/office-junk-removal`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/estate-junk-removal-bereavement`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/post-renovation-junk-removal`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/cottage-junk-removal`, changeFrequency: "weekly", priority: 0.6 },

    { url: `${BASE_URL}/en/moving-dubravka`, changeFrequency: "weekly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-karlova-ves`, changeFrequency: "weekly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-nove-mesto`, changeFrequency: "weekly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-petrzalka`, changeFrequency: "weekly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-ruzinov`, changeFrequency: "weekly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-stare-mesto`, changeFrequency: "weekly", priority: 0.6 },

    { url: `${BASE_URL}/en/apartment-junk-removal-bratislava`, changeFrequency: "weekly", priority: 0.6 },
    { url: `${BASE_URL}/en/apartment-junk-removal-trnava`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/apartment-junk-removal-nitra`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/apartment-junk-removal-senec`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/apartment-junk-removal-pezinok`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/apartment-junk-removal-galanta`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/apartment-junk-removal-sala`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/apartment-junk-removal-hlohovec`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/apartment-junk-removal-senica`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/apartment-junk-removal-malacky`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/apartment-junk-removal-levice`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/apartment-junk-removal-komarno`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/apartment-junk-removal-piestany`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/apartment-junk-removal-samorin`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/apartment-junk-removal-stupava`, changeFrequency: "weekly", priority: 0.55 },

    { url: `${BASE_URL}/en/home-junk-removal`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/home-junk-removal-galanta`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-hlohovec`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-komarno`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-levice`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-malacky`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-nitra`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-pezinok`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-piestany`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-samorin`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-sala`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-senec`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-senica`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-trnava`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-stupava`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-dubravka`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-karlova-ves`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-nove-mesto`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-petrzalka`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-ruzinov`, changeFrequency: "weekly", priority: 0.55 },
    { url: `${BASE_URL}/en/home-junk-removal-stare-mesto`, changeFrequency: "weekly", priority: 0.55 },

    { url: `${BASE_URL}/en/pricing`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/reviews`, changeFrequency: "monthly", priority: 0.5 },
    { url: `${BASE_URL}/en/contact`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/privacy-policy`, changeFrequency: "yearly", priority: 0.2 },
    { url: `${BASE_URL}/en/cookie-policy`, changeFrequency: "yearly", priority: 0.2 },
    { url: `${BASE_URL}/en/terms-of-service`, changeFrequency: "yearly", priority: 0.3 },

    { url: `${BASE_URL}/stahovanie`, changeFrequency: "weekly", priority: 0.85 },
    { url: `${BASE_URL}/vypratavanie`, changeFrequency: "weekly", priority: 0.85 },
    { url: `${BASE_URL}/stahovanie-klavira`, changeFrequency: "weekly", priority: 0.75 },
    { url: `${BASE_URL}/stahovanie-pianina`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/stahovanie-trezorov`, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE_URL}/stahovanie-strojov-zariadeni`, changeFrequency: "weekly", priority: 0.75 },

    { url: `${BASE_URL}/medzinarodne-stahovanie/anglicko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/belgicko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/ceska-republika`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/dansko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/francuzsko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/holandsko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/irsko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/madarsko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/nemecko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/norsko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/polsko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/rakusko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/spanielsko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/svajciarsko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/svedsko`, changeFrequency: "monthly", priority: 0.65 },
    { url: `${BASE_URL}/medzinarodne-stahovanie/taliansko`, changeFrequency: "monthly", priority: 0.65 },

    { url: `${BASE_URL}/en/moving`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/junk-removal`, changeFrequency: "weekly", priority: 0.65 },
    { url: `${BASE_URL}/en/machinery-moving`, changeFrequency: "weekly", priority: 0.6 },
    { url: `${BASE_URL}/en/piano-moving`, changeFrequency: "weekly", priority: 0.6 },
    { url: `${BASE_URL}/en/safe-moving`, changeFrequency: "weekly", priority: 0.6 },
    { url: `${BASE_URL}/en/upright-piano-moving`, changeFrequency: "weekly", priority: 0.6 },
    { url: `${BASE_URL}/en/basement-garage-junk-removal`, changeFrequency: "weekly", priority: 0.6 },
    { url: `${BASE_URL}/en/property-land-junk-removal`, changeFrequency: "weekly", priority: 0.6 },
    { url: `${BASE_URL}/en/hazardous-waste-removal`, changeFrequency: "weekly", priority: 0.6 },

    { url: `${BASE_URL}/en/moving-from-slovakia`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-to-slovakia`, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE_URL}/en/moving-from-slovakia-to-austria`, changeFrequency: "monthly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-from-slovakia-to-france`, changeFrequency: "monthly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-from-slovakia-to-germany`, changeFrequency: "monthly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-from-slovakia-to-ireland`, changeFrequency: "monthly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-from-slovakia-to-netherlands`, changeFrequency: "monthly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-from-slovakia-to-norway`, changeFrequency: "monthly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-from-slovakia-to-sweden`, changeFrequency: "monthly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-from-slovakia-to-switzerland`, changeFrequency: "monthly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-from-slovakia-to-uk`, changeFrequency: "monthly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-from-austria-to-slovakia`, changeFrequency: "monthly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-from-france-to-slovakia`, changeFrequency: "monthly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-from-germany-to-slovakia`, changeFrequency: "monthly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-from-netherlands-to-slovakia`, changeFrequency: "monthly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-from-uk-to-slovakia`, changeFrequency: "monthly", priority: 0.55 },
    { url: `${BASE_URL}/en/moving-from-usa-to-slovakia`, changeFrequency: "monthly", priority: 0.55 },
  ];

  return [...staticRoutes, ...blogRoutes];
}
